### ISSUE TITLE
Can't make it work in Windows 7

### ISSUE THREAD

**Issue by driglou** [s-a/electron-toaster#5]
I use nothing more than sample code, just to test the feature as I would like this notifications solution.
But when I use 
var ipc = require('ipc');
I get "(electron) ipc module is deprecated. Use require("electron").ipcRenderer instead."

Then I try 
var ipc = require('ipc-renderer');
I dont get anything in console, but nothing visual happens also. I'm new to Electron so it might be something obvious that I'm missing.

**Comment by s-a** [comment]
Pls upgrade to v2. I published a new version to npm.  Use  require("electron").ipcRenderer and. require("electron").ipcMain since electron 0.35
