### ISSUE TITLE
External templates

### ISSUE THREAD

**Issue by beshur** [s-a/electron-toaster#6]
Hi.

I tried this module and without tweaking it for myself was not very suitable.

I have a number of ideas:
- [x] Custom templates (path provided as a parameter on init)
- [ ] Additional image on the right side
- [ ] Custom preload.js as specific functionality may be required from the notification

Would you mind me creating pull-requests for these?

**Comment by beshur** [comment]
Oh, just saw the htmlFile parameter (so Custom templates are there already)

**Comment by s-a** [comment]
Yes I think the htmlFile parameter gives you the full controll to implement the features you need?

**Comment by beshur** [comment]
@s-a, well, it does.
However, I modified the code and added the preload.js on my project.
May take some time until I can make a pull-request.

Think can close for now - htmlFile should be enough for most users.
