### ISSUE TITLE
Cannot find module 'browser-window'

### ISSUE THREAD

**Issue by cosminpopescu** [s-a/electron-toaster#7]
I'm getting the cannot find module 'browser-window' error when running toastr. I'm using Electron 1.2.0.

![image](https://cloud.githubusercontent.com/assets/5416168/15704743/a4f8ab76-27f4-11e6-8e1a-b3c1f6f8f83a.png)

**Comment by s-a** [comment]
Yes, this module needs a migration to electron 1.x. PR is welcome :+1:

**Comment by afshinm** [comment]
Yeah, it doesn't work.
